steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_world
  - --gen2
  - --region=europe-west1
  - --source=.
  - --runtime=python310
  - --memory=512MB
  - --max-instances=10
  - --entry-point=hello_world
  - --trigger-bucket=poc_landing_zone
  - --trigger-location=eu
  