steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_gcs
  - --gen2
  - --region=europe-west1
  - --source=.
  - --runtime=python311
  - --memory=512MB
  - --max-instances=10
  - --entry-point=hello_gcs
  - --trigger-bucket=poc_landing_zone
  - --trigger-location=eu
  - --run-service-account=cloud-function-etl-from-gcs@dbt-for-bigquery-377112.iam.gserviceaccount.com
  - --trigger-service-account=cloud-function-etl-from-gcs@dbt-for-bigquery-377112.iam.gserviceaccount.com
  