steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - hello_world
    - --gen2
    - --runtime=python310
    - --region=europe-west1
    - --source=.
    - --entry-point=main.py
    - --trigger-event=google.storage.object.finalize
    - --trigger-resource=europe-west1
    - --run-service-account=cloud-function-sa@dbt-for-bigquery-377112.iam.gserviceaccount.com
    - --trigger-location=us
