steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_world
  - --region=europe-west1
  - --source=.
  - --runtime=python310
  - --trigger-bucket=poc_landing_zone
  - --trigger-event=google.storage.object.finalize