steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_world
  - --region=europe-west1
  - --source=.
  - --runtime=python310
  - --trigger-http
  - --timeout=540
  - --memory=512MB
  - --run-service-account=1064256876210-compute@developer.gserviceaccount.com
  - --entry-point=main
  - --trigger-bucket=poc_landing_zone
  - --quiet
  